/**
 * App Portal static catalog.
 * Generated by resource_manager.html at 2026-05-14T16:16:58.380Z
 */
const apps = [
  {
    "id": "Ajust-Image-Converter",
    "name": "Ajust-Image-Converter",
    "shortDescription": "It copies all images within the specified folder, converts them to .",
    "description": "It copies all images within the specified folder, converts them to .\npng format, and saves them to a new folder.\nThis tool optimizes images for AI training of Lora.\n\nA simple GUI tool that batch-converts images in a selected folder to PNG, saving results into a time-stamped output folder.\nOptional one-click operations include left–right mirroring, pixel-art friendly ×4 upscaling (nearest-neighbor),\naspect-ratio-preserving canvas resize, and background removal (rembg).\nWorkflow is intentionally minimal: choose a folder → start conversion.\nUsing this tool's image conversion can improve the accuracy of Lora creation to a certain extent.",
    "icon": "📦",
    "iconColor": "#2B78D3",
    "iconImage": null,
    "category": "Edit Material",
    "version": "1.0a",
    "lastUpdated": "2025-09-29",
    "requirements": "Windows10，Windows11",
    "language": "Python 3.10.4 on win32",
    "features": [
      "Batch conversion of images in a folder (PNG)",
      "Automatic image resizing",
      "Background Removal",
      "High-resolution enlargement of pixel art"
    ],
    "downloads": [
      {
        "label": "最新版をダウンロード (V1.0a)",
        "url": "https://github.com/Sadc2h4/Ajust-Image-Converter/releases/download/V1.0a/Ajust.Image.Converter.zip",
        "primary": true
      },
      {
        "label": "GitHubリポジトリを開く",
        "url": "https://github.com/Sadc2h4/Ajust-Image-Converter",
        "primary": false
      }
    ],
    "images": [
      "generated-assets/Ajust-Image-Converter-card-01.png",
      "generated-assets/Ajust-Image-Converter-card-02.png"
    ],
    "repoUrl": "https://github.com/Sadc2h4/Ajust-Image-Converter",
    "about": "This tool optimizes images for AI training of Lora. It copies all images within the specified folder, converts them to .png format, and saves them to a new folder.",
    "releaseTag": "V1.0a",
    "_source": "resource-manager"
  },
  {
    "id": "GitHub-Deploy-Tool",
    "name": "GitHub Deploy Tool",
    "shortDescription": "ローカルフォルダの内容をGitHubリポジトリへGUIでアップロードするためのWindows向けツールです．",
    "description": "ローカルフォルダの内容をGitHubリポジトリへGUIでアップロードするためのWindows向けツールです．\nGitHub認証，リポジトリ選択，フォルダ選択，コミット，pushまでを画面上で順番に実行できます．\n\nGitコマンドやGitHub CLIの操作に慣れていない場合でも，GitHubへのアップロード作業をGUIで簡略化するために作成したツールです．\n配布版はフォルダ直下の起動用exeからresources内のElectron本体を起動する形式にしています．\nNode.jsやnpm installは不要ですが，内部でgitコマンドとGitHub CLIを使用するため，配布先PCにはGitとGitHub CLIが必要です．\n通常のデプロイでは「履歴を保持」モードを使用することで，リモートリポジトリの履歴を取得した上で差分のみを通常pushできます．\n従来方式としてforce pushモードも選択できますが，リモート履歴を上書きする可能性があるため共有リポジトリでは注意が必要です．",
    "icon": "📦",
    "iconColor": "#2B78D3",
    "iconImage": null,
    "category": "Utility",
    "version": "1.0",
    "lastUpdated": "2026-05-13",
    "requirements": "Windows 10 , Windows 11",
    "language": "Electron / JavaScript",
    "features": [
      "GitHubアカウント認証状態の確認",
      "既存リポジトリの選択とリポジトリの新規作成",
      "デプロイ対象ファイルの選択",
      "gitignoreの自動作成",
      "コミットメッセージとブランチ名の指定",
      "履歴を保持した通常pushとforce push"
    ],
    "downloads": [
      {
        "label": "最新版をダウンロード (v1.0)",
        "url": "https://github.com/Sadc2h4/GitHub-Deploy-Tool/releases/download/v1.0/GitHub-Deploy-Tool_v1.0.zip",
        "primary": true
      },
      {
        "label": "GitHubリポジトリを開く",
        "url": "https://github.com/Sadc2h4/GitHub-Deploy-Tool",
        "primary": false
      }
    ],
    "images": [
      "generated-assets/GitHub-Deploy-Tool-card-01.png",
      "generated-assets/GitHub-Deploy-Tool-card-02.png",
      "generated-assets/GitHub-Deploy-Tool-card-03.png"
    ],
    "repoUrl": "https://github.com/Sadc2h4/GitHub-Deploy-Tool",
    "about": "本アプリケーションはGit bashでの手動のデプロイで操作ミスすることを防ぐために作成しました．扱いやすいelectron UIでデプロイ操作を簡略化できます．",
    "releaseTag": "v1.0",
    "_source": "resource-manager"
  },
  {
    "id": "Hocotate-Tool-Kit",
    "name": "Hocotate-Tool-Kit",
    "shortDescription": "This application is a multi-purpose command-line tool for working with Nintendo GameCube / Wii archive and 3D model formats used in Pikmin 2.",
    "description": "This application is a multi-purpose command-line tool for working with Nintendo GameCube / Wii archive and 3D model formats used in Pikmin 2.\n\nIt supports 14 conversion modes and accepts files via drag & drop, command-line arguments, or Windows right-click context menu. Dropping a BMD/BDL file runs all three BMD export modes at once (bmd2dae, bmd2fbx, bmd2obj) and places each output in a named subfolder next to the source file.\nYou can access various functions by right-clicking.",
    "icon": "📦",
    "iconColor": "#2B78D3",
    "iconImage": null,
    "category": "Pikmin Hack",
    "version": "1.25a",
    "lastUpdated": "2026-04-25",
    "requirements": "Windows10，Windows11",
    "language": "C#.NET 4.8 win x64",
    "features": [
      "supports 14 conversion modes",
      "Conversion between BMD and FBX",
      "Extracting and Compressing SZS Files",
      "Extracting Disc Data from the GameCube and Wii",
      "Launching functions via right-click"
    ],
    "downloads": [
      {
        "label": "最新版をダウンロード (v1.25a)",
        "url": "https://github.com/Sadc2h4/Hocotate-Tool-Kit/releases/download/v1.25a/Hocotate_Toolkit_v1.25a.zip",
        "primary": true
      },
      {
        "label": "GitHubリポジトリを開く",
        "url": "https://github.com/Sadc2h4/Hocotate-Tool-Kit",
        "primary": false
      }
    ],
    "images": [
      "generated-assets/Hocotate-Tool-Kit-card-01.png",
      "generated-assets/Hocotate-Tool-Kit-card-02.png",
      "generated-assets/Hocotate-Tool-Kit-card-03.png"
    ],
    "repoUrl": "https://github.com/Sadc2h4/Hocotate-Tool-Kit",
    "about": "This application is a multi-purpose command-line tool for working with Nintendo GameCube / Wii archive and 3D model formats used in Pikmin 2.   It supports 8 conversion modes and accepts files via drag & drop, command-line arguments, or Windows right-click context menu.",
    "releaseTag": "v1.25a",
    "_source": "resource-manager"
  },
  {
    "id": "Klefki-Conflu",
    "name": "Klefki-Conflu",
    "shortDescription": "本アプリケーションはConfluenceのバックアップZIPファイルを可読性の高いHTML形式に復元するツールです．",
    "description": "本アプリケーションはConfluenceのバックアップZIPファイルを可読性の高いHTML形式に復元するツールです．\n\n標準のConfluenceバックアップファイルはローカルサーバー環境の構築とConfluenceシステム内での閲覧を必要としますが，\n本アプリケーションでは改訂履歴，画像やドキュメントファイルを含むデータの約90%を簡単操作で復元可能です．",
    "icon": "📦",
    "iconColor": "#2B78D3",
    "iconImage": null,
    "category": "Data Analysis",
    "version": "1.40a",
    "lastUpdated": "2025-11-24",
    "requirements": "Windows10，Windows11",
    "language": "Python 3.10.8",
    "features": [
      "ConfluenceのバックアップZipの復元",
      "暗号化コンテンツの復元"
    ],
    "downloads": [
      {
        "label": "最新版をダウンロード (v1.40a)",
        "url": "https://github.com/Sadc2h4/Klefki-Conflu/releases/download/v1.40a/Klefki_Conflu_v1.40.zip",
        "primary": true
      },
      {
        "label": "GitHubリポジトリを開く",
        "url": "https://github.com/Sadc2h4/Klefki-Conflu",
        "primary": false
      }
    ],
    "images": [
      "generated-assets/Klefki-Conflu-card-01.png",
      "generated-assets/Klefki-Conflu-card-02.png"
    ],
    "repoUrl": "https://github.com/Sadc2h4/Klefki-Conflu",
    "about": "This Python application restores Confluence backup ZIP files into a readable HTML format. While standard Confluence backup files require setting up a local server environment and viewing them within the Confluence system, this application enables restoration of approximately 90% of the data, including revision history.",
    "releaseTag": "v1.40a",
    "_source": "resource-manager"
  },
  {
    "id": "Lotad-Icon-Editor",
    "name": "Lotad Icon Editor",
    "shortDescription": "BPRJ/BPRE向けのポケモンアイコン確認用ツールです．Romイメージだけでなくフォルダにも対応しています．",
    "description": "BPRJ/BPRE向けのポケモンアイコン確認用ツールです．Romイメージだけでなくフォルダにも対応しています．\n\n本ツールの製作当初は『既存ポケモンのアイコン（アニメーション付き）を閲覧できるサイトが見つからなくなった』ことから\n本家で使用されるvanillaのポケモン手持ちアイコンを一覧で並べて確認するために作成していました．\nRom imageへの直接反映や足跡アイコンへの対応，多言語化など複数の要望を追加していくうちにポケモンのアイコン周りを\n雑に且つ簡単に操作できる編集用エディタとして大幅に内容が追加された経緯があります．",
    "icon": "📦",
    "iconColor": "#2B78D3",
    "iconImage": null,
    "category": "Pokemon Hack",
    "version": "2.0a",
    "lastUpdated": "2025-09-04",
    "requirements": "Windows 10 , Windows 11",
    "language": "C#.NET 4.8",
    "features": [
      "アイコンの確認・編集（ファイル，Rom image両方に対応）",
      "アイコンのパレット確認・編集",
      "足跡の確認・編集"
    ],
    "downloads": [
      {
        "label": "最新版をダウンロード (v2.0a)",
        "url": "https://github.com/Sadc2h4/Lotad-Icon-Editor/releases/download/v2.0a/Lotad.Icon.Editor.zip",
        "primary": true
      },
      {
        "label": "GitHubリポジトリを開く",
        "url": "https://github.com/Sadc2h4/Lotad-Icon-Editor",
        "primary": false
      }
    ],
    "images": [
      "generated-assets/Lotad-Icon-Editor-card-01.png",
      "generated-assets/Lotad-Icon-Editor-card-02.png",
      "generated-assets/Lotad-Icon-Editor-card-03.png"
    ],
    "repoUrl": "https://github.com/Sadc2h4/Lotad-Icon-Editor",
    "about": "BPRJ/BPRE向けのポケモンアイコン確認用ツールです．Romイメージだけでなくフォルダにも対応しています．",
    "releaseTag": "v2.0a",
    "_source": "resource-manager"
  },
  {
    "id": "Meta-Data-Search",
    "name": "Meta-Data-Search",
    "shortDescription": "This application was created to visualize information such as prompts, models,",
    "description": "This application was created to visualize information such as prompts, models,\nand Lora used in image generation from metadata within images created by generative AI like Stable Diffusion.\n\nThis application was created to extract generation information from the metadata within output images,\nas it was cumbersome to manually store all the details—such as the prompts and Lora weights used during\ngeneration when creating images with Stable Diffusion-based generative AI.\nIt extracts metadata from Stable Diffusion images (ComfyUI / AUTOMATIC1111, etc.) and\nsupports loading PNG / JPG / WebP files (with preview support) via drag-and-drop or buttons.\nThis is the light version, which omits the AI prompt functionality to reduce the overall file size.\nIf you primarily want to use it for metadata extraction, this version might be preferable.",
    "icon": "📦",
    "iconColor": "#2B78D3",
    "iconImage": null,
    "category": "Data Analysis",
    "version": "1.1a",
    "lastUpdated": "2025-09-19",
    "requirements": "Windows 10 , Windows 11",
    "language": "C# .NET 6.0",
    "features": [
      "Identifying signs of AI use in images",
      "Tracking of the LoRA models and prompts used",
      "Check for traces of watermarks"
    ],
    "downloads": [
      {
        "label": "最新版をダウンロード (V1.1a)",
        "url": "https://github.com/Sadc2h4/Meta-Data-Search/releases/download/V1.1a/Meta_DataSearch_1.1a_light.zip",
        "primary": true
      },
      {
        "label": "GitHubリポジトリを開く",
        "url": "https://github.com/Sadc2h4/Meta-Data-Search",
        "primary": false
      }
    ],
    "images": [
      "generated-assets/Meta-Data-Search-card-01.png"
    ],
    "repoUrl": "https://github.com/Sadc2h4/Meta-Data-Search",
    "about": "This application was created to visualize information such as prompts, models, and Lora used in image generation from metadata within images created by generative AI like Stable Diffusion.",
    "releaseTag": "V1.1a",
    "_source": "resource-manager"
  },
  {
    "id": "Morinohito-Editor",
    "name": "Morinohito-Editor",
    "shortDescription": "『動画内の特定エリアだけを切り取って保存』する，というニッチな作業のために作成した簡易動画トリミングツールです．",
    "description": "『動画内の特定エリアだけを切り取って保存』する，というニッチな作業のために作成した簡易動画トリミングツールです．\n\n本ツールは『動画画面内の特定のエリアだけを切り取って別の動画として保存』の機能を持つツールが何処にも見つからなかったため，\n手元のPCとこのツールのみで動画の特定座標エリアを切り取って素材化する動作を簡潔できるようにする目的で作成された簡易動画編集ツールです．\n一応，通常の『動画の特定時間部分を切り出すツール』として使用することも可能となっています．\n『動画内で特定の場所の数秒間だけが素材として欲しい』のような場面で役に立つかもしれません．",
    "icon": "📦",
    "iconColor": "#2B78D3",
    "iconImage": null,
    "category": "Edit Material",
    "version": "1.4a",
    "lastUpdated": "2025-09-29",
    "requirements": "Windows10，Windows11",
    "language": "Python 3.10.4 on win32",
    "features": [
      "MP4，GIF，MKVファイルの動画のトリミング保存",
      "動画素材作成"
    ],
    "downloads": [
      {
        "label": "最新版をダウンロード (v1.4a)",
        "url": "https://github.com/Sadc2h4/Morinohito-Editor/releases/download/v1.4a/Morinohito_Editor.zip",
        "primary": true
      },
      {
        "label": "GitHubリポジトリを開く",
        "url": "https://github.com/Sadc2h4/Morinohito-Editor",
        "primary": false
      }
    ],
    "images": [
      "generated-assets/Morinohito-Editor-card-01.png",
      "generated-assets/Morinohito-Editor-card-02.png"
    ],
    "repoUrl": "https://github.com/Sadc2h4/Morinohito-Editor",
    "about": "動画内の特定エリアだけを切り取って保存する為に作成した簡易動画トリミングツールです．『動画内で特定の場所の数秒間だけが素材として欲しい』のような，素材作成などの場面で活用できる内容になっています．",
    "releaseTag": "v1.4a",
    "_source": "resource-manager"
  },
  {
    "id": "Mudkip-Script-Editor",
    "name": "Mudkip-Script-Editor",
    "shortDescription": "ポケモンFR（BPRJ）向けの技関連スクリプトの効果確認，技アニメーションの確認，",
    "description": "ポケモンFR（BPRJ）向けの技関連スクリプトの効果確認，技アニメーションの確認，\n表示パターンの設定，タイプのチャート表示などの機能を纏めた統合編集ツールです．\n\n本アプリケーションは技情報の編集以外にスクリプトの効果確認，技アニメーションの確認，表示パターンの設定，タイプのチャート編集など，\n技作成の機能に特化した統合ツールとして作成しました．\nポケモンFR（BPRJ）の技編集ツールとしてはSkillEditor，poke-Syntheなどがありますが，本アプリケーションでは\n技IDごとに情報を個別で取得して編集可能な他，複雑なスクリプトの効果内容やジャンプ先を可視化するなど，バイナリベースでより高度な編集が可能です．\n使いにくい部分もあると思いますが，少なくともバイナリエディタでの直書き込みと比較したら編集が楽な気がします()",
    "icon": "📦",
    "iconColor": "#2B78D3",
    "iconImage": null,
    "category": "Pokemon Hack",
    "version": "1.3a",
    "lastUpdated": "2025-09-05",
    "requirements": "Windows 10 , Windows 11",
    "language": "C#.NET 4.8",
    "features": [
      "Romイメージ内の技データをExcelとしてエクスポート",
      "技効果スクリプトの内容閲覧，編集",
      "技アニメスクリプトの内容閲覧，編集",
      "技実行時の言い回しパターン編集",
      "タイプ相性チャート閲覧，編集",
      "戦闘定型文閲覧",
      "Stirlingへの外部参照補助"
    ],
    "downloads": [
      {
        "label": "最新版をダウンロード (v1.3a)",
        "url": "https://github.com/Sadc2h4/Mudkip-Script-Editor/releases/download/v1.3a/Meta_DataSearch_light.zip",
        "primary": true
      },
      {
        "label": "Mudkip.Script.Editor.1.3a.zip",
        "url": "https://github.com/Sadc2h4/Mudkip-Script-Editor/releases/download/v1.3a/Mudkip.Script.Editor.1.3a.zip",
        "primary": false
      },
      {
        "label": "GitHubリポジトリを開く",
        "url": "https://github.com/Sadc2h4/Mudkip-Script-Editor",
        "primary": false
      }
    ],
    "images": [
      "generated-assets/Mudkip-Script-Editor-card-01.png",
      "generated-assets/Mudkip-Script-Editor-card-02.png",
      "generated-assets/Mudkip-Script-Editor-card-03.png"
    ],
    "repoUrl": "https://github.com/Sadc2h4/Mudkip-Script-Editor",
    "about": "ポケモンFR（BPRJ）向けの技関連スクリプトの効果確認，技アニメーションの確認，表示パターンの設定，タイプのチャート表示などの機能を纏めた統合編集ツールです．",
    "releaseTag": "v1.3a",
    "_source": "resource-manager"
  },
  {
    "id": "Museum-of-Memories",
    "name": "Museum-of-Memories",
    "shortDescription": "About 本アプリケーションはピクトスクエアの画面を再現するために作成されました．会場の雰囲気を再現しつつピクトスクエアにはない機能を幾つか追加した『ピクスク再現ツール』です．",
    "description": "About 本アプリケーションはピクトスクエアの画面を再現するために作成されました．会場の雰囲気を再現しつつピクトスクエアにはない機能を幾つか追加した『ピクスク再現ツール』です．\n\nオフラインツールのためリアルタイムでのオンライン通信やお絵描き掲示板，キャラクターを彩るエフェクトの機能等はついていませんが，\nオフラインのアプリとして『デコレーション機能』『キャラクターのダッシュ/位置の微調整』など，ピクスク会場にはない専用の要素を沢山追加しています．",
    "icon": "📦",
    "iconColor": "#2B78D3",
    "iconImage": null,
    "category": "PictSquare",
    "version": "1.2.1a",
    "lastUpdated": "2025-10-07",
    "requirements": "Windows10，Windows11",
    "language": "Python 3.10.8",
    "features": [
      "PictSquareの会場再現",
      "好きな素材を置いて記念撮影",
      "ちょっとしたミニゲーム（隠れキャラ探しTA）",
      "秘密のコードと隠しアイテム（イベント限定）"
    ],
    "downloads": [
      {
        "label": "最新版をダウンロード (V1.2.1a)",
        "url": "https://github.com/Sadc2h4/Museum-of-Memories/releases/download/V1.2.1a/Museum_of_Memories.zip",
        "primary": true
      },
      {
        "label": "GitHubリポジトリを開く",
        "url": "https://github.com/Sadc2h4/Museum-of-Memories",
        "primary": false
      }
    ],
    "images": [
      "generated-assets/Museum-of-Memories-card-01.png",
      "generated-assets/Museum-of-Memories-card-02.png",
      "generated-assets/Museum-of-Memories-card-03.png"
    ],
    "repoUrl": "https://github.com/Sadc2h4/Museum-of-Memories",
    "about": "本アプリケーションはピクトスクエアの画面を再現するために作成されました．会場の雰囲気を再現しつつピクトスクエアにはない機能を幾つか追加した『ピクスク再現ツール』です．",
    "releaseTag": "V1.2.1a",
    "_source": "resource-manager"
  },
  {
    "id": "Ninja-Gecho",
    "name": "Ninja_Gecho",
    "shortDescription": "画像の背景透過を手軽に行うための Windows 向け PNG transparency editor です。",
    "description": "画像の背景透過を手軽に行うための Windows 向け PNG transparency editor です。\n塗りつぶし、色選択、矩形、消しゴム、主線保護塗りつぶしに対応しています。\n\nNinja_Gecho は、白背景や単色背景のイラスト・素材画像を PNG 透過画像へ変換するための desktop application です。\n元アプリ「手軽に透明png」の操作感を参考にしつつ、現在の表示倍率でピクセルを保持したリサイズ保存ができる機能を追加しています。\n主線が切れている線画では、専用の主線保護塗りつぶしモードを使うことで、線抜け部分から内側まで背景透過が流れ込む問題を軽減します。",
    "icon": "📦",
    "iconColor": "#2B78D3",
    "iconImage": null,
    "category": "Image Tool / 画像編集",
    "version": "1.1",
    "lastUpdated": "2026-05-14",
    "requirements": "Windows 10 , Windows 11 / x64",
    "language": "C# / .NET 8 / Windows Forms",
    "features": [],
    "downloads": [
      {
        "label": "最新版をダウンロード (v1.1)",
        "url": "https://github.com/Sadc2h4/Ninja-Gecho/releases/download/v1.1/Ninja_Gecho_v1.1.zip",
        "primary": true
      },
      {
        "label": "GitHubリポジトリを開く",
        "url": "https://github.com/Sadc2h4/Ninja-Gecho",
        "primary": false
      }
    ],
    "images": [],
    "repoUrl": "https://github.com/Sadc2h4/Ninja-Gecho",
    "about": "本アプリケーションは画像の背景や指定した場所を手軽に透過して保存するために作成されました。画像の透過以外にも解像度を維持したサイズ変更するなど、手作業だと調整が大変な作業も簡単に実施できるようにしています。",
    "releaseTag": "v1.1",
    "_source": "resource-manager"
  },
  {
    "id": "PikiModel-Randomizer",
    "name": "PikiModel-Randomizer",
    "shortDescription": "This application is a GUI tool for batch-generating scale variants of Pikmin 2 character models (BMD files).",
    "description": "This application is a GUI tool for batch-generating scale variants of Pikmin 2 character models (BMD files).\nScale ranges can be configured individually for each body part\nhead, leaf, body, legs, arms, and eyes.\n\n本アプリケーションはPikmin 2で使用されるキャラクターモデル（BMDファイル）のスケールをランダムに変化させたバリアントを一括生成するGUIツールです．\n頭・葉・体・脚・腕・目といった部位ごとにスケールの変動範囲を細かく設定でき，シード値を指定することで再現性のある結果を得ることができます．\n変換処理には外部ツール Hocotate Toolkit を使用します． 普段見慣れたキャラクターモデルもこのアプリケーションでランダマイズすると違った雰囲気を楽しめるかもしれません。",
    "icon": "📦",
    "iconColor": "#2B78D3",
    "iconImage": null,
    "category": "Pikmin Hack",
    "version": "1.1b",
    "lastUpdated": "2026-04-10",
    "requirements": "Windows10，Windows11",
    "language": "Python 3.10.8",
    "features": [
      "BMDデータのランダム編集",
      "派生パターン作成"
    ],
    "downloads": [
      {
        "label": "最新版をダウンロード (v1.1b)",
        "url": "https://github.com/Sadc2h4/PikiModel-Randomizer/releases/download/v1.1b/PikiModel_Randomizer_v1.1b.zip",
        "primary": true
      },
      {
        "label": "GitHubリポジトリを開く",
        "url": "https://github.com/Sadc2h4/PikiModel-Randomizer",
        "primary": false
      }
    ],
    "images": [
      "generated-assets/PikiModel-Randomizer-card-01.png",
      "generated-assets/PikiModel-Randomizer-card-02.png"
    ],
    "repoUrl": "https://github.com/Sadc2h4/PikiModel-Randomizer",
    "about": "This application is a GUI tool for batch-generating scale variants of Pikmin 2 character models (BMD files). Scale ranges can be configured individually for each body part — head, leaf, body, legs, arms, and eyes. A fixed seed value produces reproducible results. Conversion relies on the external tool Hocotate Toolkit. Even familiar character model",
    "releaseTag": "v1.1b",
    "_source": "resource-manager"
  },
  {
    "id": "Web-File-Gulpin",
    "name": "Web-File-Gulpin",
    "shortDescription": "本アプリケーションはウェブサイトのURLから構成ファイルを纏めて取得する目的で作成されたデータ取得ツールです．",
    "description": "本アプリケーションはウェブサイトのURLから構成ファイルを纏めて取得する目的で作成されたデータ取得ツールです．\nURLを入れて実行ボタンを押すだけでページ内のコンテンツを丸ごと取得できます．\n\nホームページのバックアップや，大量に取得が必要なデータファイルをまとめて取得する等の目的で使用ができます．\nwebページの保存でも同じことが可能ですが，本アプリはカテゴリ分けやインデックス作成を自動で実行できるため管理のしやすさに重点を置いています．",
    "icon": "📦",
    "iconColor": "#2B78D3",
    "iconImage": null,
    "category": "Data Analysis",
    "version": "1.1f",
    "lastUpdated": "2026-03-31",
    "requirements": "Windows10，Windows11",
    "language": "Python 3.10.4",
    "features": [
      "ホームーページからのデータ一括取得",
      "jsonファイル抽出",
      "画像データ抽出"
    ],
    "downloads": [
      {
        "label": "最新版をダウンロード (v1.1f)",
        "url": "https://github.com/Sadc2h4/Web-File-Gulpin/releases/download/v1.1f/Web_File_Gulpin_1.1f.zip",
        "primary": true
      },
      {
        "label": "GitHubリポジトリを開く",
        "url": "https://github.com/Sadc2h4/Web-File-Gulpin",
        "primary": false
      }
    ],
    "images": [
      "generated-assets/Web-File-Gulpin-card-01.png",
      "generated-assets/Web-File-Gulpin-card-02.png",
      "generated-assets/Web-File-Gulpin-card-03.png"
    ],
    "repoUrl": "https://github.com/Sadc2h4/Web-File-Gulpin",
    "about": "本アプリケーションはウェブサイトのURLからホームページ構成ファイル，ダウンロードリンクに登録された実ファイル，登録画像などを一括で取得する目的で作成されました． ホームページのバックアップや，大量に取得が必要なデータファイルをまとめて取得する等の目的で使用ができます． （webページの保存でも同じことが可能ですが，本アプリはカテゴリ分けやインデックス作成を自動で実行できるため管理のしやすさに重点を置いています）",
    "releaseTag": "v1.1f",
    "_source": "resource-manager"
  }
];
